service: backslack

frameworkVersion: ">=1.17.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: v0
  region: ap-northeast-1
  cfLogs: true
  apiKey: false

functions:
  hook:
    handler: handler.hook
    events:
      - http:
          path: hook
          method: post
          cors: false
          integration: lambda-proxy
