service: backslack

frameworkVersion: "=1.7.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: v0
  region: ap-northeast-1
  cfLogs: true
  apiKey: false

functions:
  hook:
    handler: handler.hook
    events:
      - http:
          path: hook
          method: post
          cors: false
          integration: lambda-proxy
